### PR TITLE
Add makefile

### PR DESCRIPTION
**Pull request by beansgum**
Using a makefile would enable building a binary with build flags & variables while targeting multiple os.

### CODE REVIEW

**Review by Sirmorrison — COMMENTED** [review]
It would be nice to update the readme doc so we know exactly how to build using the makefile changes.

**Review by Sirmorrison — COMMENTED** [review]
image
 i get the error when i try to run `make` on windows.

**Comment by beansgum** [comment]
@Sirmorrison  it  errors because you’re trying to build for freebsd and cross compilation isn’t possible yet.

**Review by Sirmorrison — DISMISSED** [review]
Tested and works fine.

**Review by dreacot — APPROVED** [review]

**Review by Sirmorrison — APPROVED** [review]

**Pull request merged**
