### PR TITLE
Update sign message page to new ui

### LINKED ISSUE #285: implement new mockup design on sign message page
update the sign message page to the new UI design. Below is one of the screenshots of the new UI

Screenshot 2020-12-25 at 15 53 04

### PR DESCRIPTION
**Pull request by Sirmorrison**
Fix #285 

This PR updates  the sign message page to the new ui mock up design.

image

image

image

### CODE REVIEW

**Comment by oshorefueled** [comment]
I shouldn't get an error message on the page before even inputting any value into the input field
Screenshot 2021-01-04 at 20 31 24

there's no message about on the second input in the mockups
Screenshot 2021-01-04 at 20 46 58
 
there should be a space between "address" and "to"
Screenshot 2021-01-04 at 20 48 53

**Comment by Sirmorrison** [comment]
> I shouldn't get an error message on the page before even inputting any value into the input field
> Screenshot 2021-01-04 at 20 31 24
> 
> there's no message about on the second input in the mockups
> Screenshot 2021-01-04 at 20 46 58
> 
> there should be a space between "address" and "to"
> Screenshot 2021-01-04 at 20 48 53

Resolved.

**Comment by oshorefueled** [comment]
For some reason, the verify that an address belongs to a wallet isn't consistent.  I get the "Added not owned by this wallet" error. I have only one wallet created, so there's no way I'm mixing the addresses up. 

Screenshot 2021-01-08 at 14 14 26

Generated signature isn't cleared when I exit the sign message page. 
Screenshot 2021-01-08 at 14 18 26

**Comment by Sirmorrison** [comment]
https://user-images.githubusercontent.com/27733432/104115383-3690b480-530f-11eb-9bf4-dfae8ca5dec0.mov

**Review by oshorefueled — APPROVED** [review]

**Pull request merged**
