### PR TITLE
Fix incorrect duration between current time and transaction time

### LINKED ISSUE #748: TX date/time ago bug
on the transaction page, transactions are less than a week old, yet it shows up as a month old.

image

### PR DESCRIPTION
**Pull request by devchoplife**
Closes #748 

This PR fixes a bug where transactions less than a month old are being displayed as being 1 month old.

### CODE REVIEW

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
image
 
issue persist

**Review by dreacot — DISMISSED** [review]
LGTM, @Sirmorrison please give a second opinion on this

**Comment by dreacot** [comment]
@devchoplife please update the title of this PR to be clearer

**Comment by Sirmorrison** [comment]
it looks good in resolving the issue above. However, i still noticed some irregularities.

image

These transactions are not up to 2 months yet. it should be `1 month ago`

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
There is a regression in your code as almost all transactions are showing 11 months ago.
image

**Review by Sirmorrison — APPROVED** [review]

**Pull request merged**
