### PR TITLE
update wallet settings page to mock up

### PR DESCRIPTION
**Pull request by Sirmorrison**
Update wallet settings page the to updated UI.

### CODE REVIEW

**Comment by devchoplife** [comment]
I notticed this and I am not sure if that is the expected behaviour:
The click effect only affects the text rows on wallet settings page. See image below:
Screenshot from 2021-11-08 07-33-13

**Comment by Sirmorrison** [comment]
From my end, there is no hover effect.
image

**Comment by dreacot** [comment]
What @devchoplife is referring to is the clickable area for the menu, it should be expanded to be same with that of currency conversion or language settings on the settings page

**Comment by Sirmorrison** [comment]
> What @devchoplife is referring to is the clickable area for the menu, it should be expanded to be same with that of currency conversion or language settings on the settings page

Not exactly. He was referring to the highlight of the app labels when the button is clicked.

Also, i dont see the need for increasing the width of the click area as it has no impact on the features functionality.

**Comment by devchoplife** [comment]
> > What @devchoplife is referring to is the clickable area for the menu, it should be expanded to be same with that of currency conversion or language settings on the settings page
> 
> Not exactly. He was referring to the highlight of the app labels when the button is clicked.
> 
> Also, i dont see the need for increasing the width of the click area as it has no impact on the features functionality.

I was referring to the clickable area as @dreacot  mentioned.

**Review by dreacot — APPROVED** [review]

**Pull request merged**
