### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by francov99**

### CODE REVIEW

**Comment by C-ollins** [comment]
@francov99 this looks ready, is this pull request still a draft?

**Comment by Clariceco** [comment]
@francov99 what is the status of this PR you have open? When will you be able to complete it so that we can merge it?

**Comment by francov99** [comment]
> @francov99 what is the status of this PR you have open? When will you be able to complete it so that we can merge it?

@Clariceco sorry for the delay. I was finishing other tasks. Tomorrow I will advance in this PR as well. I hope to finish it on Tuesday.

**Comment by Clariceco** [comment]
@Sirmorrison can you please merge this

**Comment by Sirmorrison** [comment]
> @Sirmorrison can you please merge this

The PR failed build due to some lint errors. @francov99 kindly have this resolved and we can proceed to

**Comment by francov99** [comment]
Done @Sirmorrison , I already fixed the issues.

**Review by Sirmorrison — APPROVED** [review]

**Review by dreacot — APPROVED** [review]

**Pull request merged**
