### PR TITLE
Update color and icon on top bar

### LINKED ISSUE #1018: Incorrect gradient color and arrow on main page
The colour used on the main page gradient seems deeper than what we have on the Figma mock-up. Also, the "back" arrow seems narrower. See the image below:

image

### PR DESCRIPTION
**Pull request by JustinBeBoy**
Resolve #1018 

**Screenshot**
image

### CODE REVIEW

**Comment by Sirmorrison** [comment]
image

The gradient looks needs to be balanced on the left also, from the mockup, the `GoDCR` text has been removed. also, the balance on the left need to look like the mockup when currency conversion is active.
image

image

**Comment by JustinBeBoy** [comment]
> image
> 
> The gradient looks needs to be balanced on the left also, from the mockup, the `GoDCR` text has been removed. also, the balance on the left need to look like the mockup when currency conversion is active. image
> 
> image

What exactly mockup UI we need to implement ? Can you send me a link?

**Comment by Sirmorrison** [comment]
> > image
> > The gradient looks needs to be balanced on the left also, from the mockup, the `GoDCR` text has been removed. also, the balance on the left need to look like the mockup when currency conversion is active. image
> > image
> 
> What exactly mockup UI we need to implement ? Can you send me a link?

https://www.figma.com/file/e0cYaAzkXyXXPY00v23cQY/GoDCR-%26-DCRMobile?node-id=4143%3A175347

**Review by devchoplife — CHANGES_REQUESTED** [review]
The colour on the left is perfect but the colour on the right looks sharper than what is provided on the mockup. See the image below:

image

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
image

there is this shadow that does not leave after clicking the hide icon.

**Comment by Sirmorrison** [comment]
Also, kindly rebase this PR.

**Comment by JustinBeBoy** [comment]
> image
> 
> there is this shadow that does not leave after clicking the hide icon.

seem like the issue from IconButton, I have tried with other button it the same and need to fix in other PR

**Review by devchoplife — COMMENTED** [review]
Everything looks good except the shadow that lingers after clicking on the hide icon. Also, does this PR add a section for the USD balance layout?

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
I had to rebase the PR for the app level setting page on master to reflect in this PR so as to test the exchange rate feature. (I requested the PR rebase for this reason but it was obviously ignored).


https://user-images.githubusercontent.com/27733432/182305820-ec823a35-5ccb-40ee-95b2-f9763d4ceec9.mov

So after setting the currency conversion from the setting, i still dont see the USD exchange rate on the navigation panel. (see video above).

image

**Comment by dreacot** [comment]
Screenshot from 2022-08-03 10-47-08

Based on the figma design the trailing "DCR" should be bigger and bolder

**Comment by dreacot** [comment]
> > image
> > there is this shadow that does not leave after clicking the hide icon.
> 
> seem like the issue from IconButton, I have tried with other button it the same and need to fix in other PR

this happens with other buttons that have a hover effect, so it's not related to this PR as stated

**Comment by JustinBeBoy** [comment]
> > > image
> 
> > > there is this shadow that does not leave after clicking the hide icon.
> 
> > 
> 
> > seem like the issue from IconButton, I have tried with other button it the same and need to fix in other PR
> 
> 
> 
> this happens with other buttons that have a hover effect, so it's not related to this PR as stated

i tried on other IconButtons it will happen if you don't show other modals on top of them

**Review by dreacot — COMMENTED** [review]
other than this https://github.com/planetdecred/godcr/pull/1028#issuecomment-1203728047, LGTM

**Review by Sirmorrison — APPROVED** [review]

**Pull request merged**
