### PR TITLE
Fixed the Account Field error bug

### LINKED ISSUE #442: amount input field error message
error message on input field doesn't get cleared after inputting sendable amount. 

Screenshot 2021-05-29 at 08 13 05

### PR DESCRIPTION
**Pull request by devchoplife**
This resolves #442

### CODE REVIEW

**Comment by oshorefueled** [comment]
No error is displayed when I input a value greater than the spendable balance

Screenshot 2021-06-11 at 00 55 49

**Comment by Sirmorrison** [comment]
This was part of the issue that i was referring to in #452 . You mentioned that @C-ollins was working on it as part of the general code clean up PR #450.

**Comment by oshorefueled** [comment]
> This was part of the issue that i was referring to in #452 . You mentioned that @C-ollins was working on it as part of the general code clean up PR #450.

The input field returns an error on the master branch when an amount greater than the available spendable is inputted. It only has that behaviour on this PR.

**Comment by devchoplife** [comment]
> > This was part of the issue that i was referring to in #452 . You mentioned that @C-ollins was working on it as part of the general code clean up PR #450.
> 
> The input field returns an error on the master branch when an amount greater than the available spendable is inputted. It only has that behaviour on this PR.

The error does not show up on master branch on my end.
Screenshot from 2021-06-12 07-29-48

It does not show up on my PR also

**Comment by oshorefueled** [comment]
input an address into the address field then type in an amount. Test it for both your branch and the master branch. The amount field validation should be independent of the address field. A fix for that can be done on this PR.

**Comment by devchoplife** [comment]
> input an address into the address field then type in an amount. Test it for both your branch and the master branch. The amount field validation should be independent of the address field. A fix for that can be done on this PR.

After putting a valid wallet address and an amount greater than Spendable amount. An error was thrown on maaster branch. However an error was not thrown when i did the same on my PR.

I will work on fixing that and also separating the amount validation from wallet address field.

**Review by oshorefueled — APPROVED** [review]

**Pull request merged**
